openapi: "3.0.0"

info:
  title: "Simplelogin"
  version: "1.0.0"

servers:
  - url: "/"

paths:
  /api/alias/random/new:
    post:
      description: ""
      responses:
        "201":
          description: ""
          content:
            application/json:
              example: |
                {
                  "alias": "blastoffs_endotracheitis@simplelogin.ruekov.eu",
                  "creation_date": "2025-04-10 18:11:35+00:00",
                  "creation_timestamp": 1744308695,
                  "disable_pgp": false,
                  "email": "blastoffs_endotracheitis@simplelogin.ruekov.eu",
                  "enabled": true,
                  "id": 5,
                  "latest_activity": null,
                  "mailbox": {
                    "email": "admin@ruekov.eu",
                    "id": 1
                  },
                  "mailboxes": [
                    {
                      "email": "admin@ruekov.eu",
                      "id": 1
                    }
                  ],
                  "name": null,
                  "nb_block": 0,
                  "nb_forward": 0,
                  "nb_reply": 0,
                  "note": "Website: https://simplelogin.ruekov.eu/dashboard/api_key. Generated by Bitwarden.",
                  "pinned": false,
                  "support_pgp": false
                }
